exclude: '^(mypyc/external/)|(mypy/typeshed/)'  # Exclude all vendored code from lints
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0  # must match test-requirements.txt
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: https://github.com/hauntsaninja/black-pre-commit-mirror
    rev: 23.3.0  # must match test-requirements.txt
    hooks:
      - id: black
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.272  # must match test-requirements.txt
    hooks:
      - id: ruff
        args: [--exit-non-zero-on-fix]
