repos:
  - repo: https://github.com/psf/black
    rev: 22.12.0  # must match test-requirements.txt
    hooks:
      - id: black
  - repo: https://github.com/pycqa/isort
    rev: 5.11.5  # must match test-requirements.txt
    hooks:
      - id: isort
  - repo: https://github.com/pycqa/flake8
    rev: 5.0.4  # must match test-requirements.txt
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear==22.12.6  # must match test-requirements.txt
          - flake8-noqa==1.3.0       # must match test-requirements.txt
