sudo: false
language: python
# cache package wheels (1 cache per python version)
cache: pip
python:
  - "3.4"
  # Specifically request 3.5.1 because we need to be compatible with that.
  - "3.5.1"
  - "3.6"
  - "3.7-dev"

install:
  - pip install -U pip setuptools wheel
  - pip install -r test-requirements.txt
  - python2 -m pip install --user typing
  - pip install .

script:
  - pytest -n12
  - if [[ $TRAVIS_PYTHON_VERSION == '3.6' ]]; then flake8 -j0; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '3.5.1' ]]; then python3 -m mypy --config-file mypy_self_check.ini -p mypy; fi
