sudo: false
language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
  # Pypy build is disaabled because it doubles the travis build time, and it rarely fails
  # unless one one of the other builds fails.
  # - "pypy3"

install:
  - pip install -r test-requirements.txt
  - python setup.py install

script: bash travis.sh

notifications:
  irc:
    channels:
      - "chat.freenode.net##mypy"
    use_notice: true
