sudo: false
language: python
python:
  - "3.3"
  - "3.4"
  # Specifically request 3.5.1 because we need to be compatible with that.
  - "3.5.1"
  - "3.6"
  - "3.7-dev"
  # Pypy build is disabled because it doubles the travis build time, and it rarely fails
  # unless one one of the other builds fails.
  # - "pypy3"

install:
  - pip install -r test-requirements.txt
  - python setup.py install

script:
  - python runtests.py -x lint -j16
  - if [[ $TRAVIS_PYTHON_VERSION == '3.6' ]]; then flake8; fi
