sudo: false
language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  # Pypy build is disabled because it doubles the travis build time, and it rarely fails
  # unless one one of the other builds fails.
  # - "pypy3"

install:
  - pip install -r test-requirements.txt
  - python setup.py install

script:
  - python runtests.py -v

notifications:
  irc:
    channels:
      - "chat.freenode.net#python-mypy"
    use_notice: true
